services:
  php_app:
    build: .
    container_name: app_php
    ports:
      - "8080:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    volumes:
      - mydb_data:/var/lib/mysql

volumes:
  mydb_data:
