apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php-app
        image: fffeeeeeee/php-app-mysql
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
